version: "3.9"

services:
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"

  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: backend
      args:
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    env_file:
      - ./.env
    environment:
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
    depends_on:
      - db

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: frontend-dev
    ports:
      - "3000:3000"
    volumes:
      - ./app/frontend:/app
    command: npm run start

  nginx:
    image: nginx:latest
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - app
      - frontend

volumes:
  postgres_data: