version: "3.9.6"

services:
  app:
    build:
      context: .
      args:
        - DEV=true
      target: app-image
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: >
      sh -c "python manage.py  runserver 0.0.0.0:8000"
    depends_on:
      - frontend

  frontend:
    build:
      context: .
      target: frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/frontend
    command: sh -c "npm start"
