version: "3.9"

services:
  app:
    build:
      context: .
      args:
        - DEV=true
      target: app-image
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - frontend

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: frontend-dev
    ports:
      - "3000:3000"
    volumes:
      - ./app/frontend:/app
    command: npm start

  nginx:
    image: nginx:latest
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - app