# Generated by Django 4.2.9 on 2024-01-17 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_product_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShoppingAddress',
            new_name='ShippingAddress',
        ),
    ]
